<?php
/**
 * @version		1 country $
 * @package		country
 * @copyright	Copyright © 2011 - All rights reserved.
 * @license		GNU/GPL
 * @author		ketan
 * @author mail	ketantada@yahoo.co.in
 * @website		ketantada.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Require the base controller
require_once (JPATH_COMPONENT.DS.'controller.php');

// Create the controller
$controller = new countryController();

// Perform the Request task
$controller->execute(JRequest::getVar('task', null, 'default', 'cmd'));
$controller->redirect();
?>