<?php
/**
 * @version		1 country $
 * @package		country
 * @copyright	Copyright © 2011 - All rights reserved.
 * @license		GNU/GPL
 * @author		ketan
 * @author mail	ketantada@yahoo.co.in
 * @website		ketantada.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
<h1><?php echo $this->greeting; ?></h1>

?>
