<?php 

/**
 * Joomla! 1.5 component mycomponent
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_mycomponent
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


jimport( 'joomla.application.component.controller' );

 /**
  * Mycomponent Component Controller
  *
  * @package Mycomponent
  */

  class mycomponentController extends JController
  {
		/**
		 * Method to show a mycomponent view
		 */
		function display()
		{
			 // Set a default view if none exists
			 if ( ! JRequest::getCmd( 'view' ) ) {
					JRequest::setVar('view', 'categories' );
			 }
		  	 //update the hit count for the item
  		  	 if(JRequest::getCmd('view') == 'item')
  			 {
  				$model =& $this->getModel('item');
  				$model->hit();
 			 }
 		parent::display();
  		}
  }